// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zptugzrnhzlcmqhyxddt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwdHVnenJuaHpsY21xaHl4ZGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzI1ODQsImV4cCI6MjA2Njg0ODU4NH0.V4BWhQddHnT2Gi6xNbLn4KrwN0LjcE7MClEkCGG-0v8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});